На данном семинаре мы изучим библиотеку [numpy](https://numpy.org/). numpy - очень удобная и быстрая библиотека, которая предсоставляет возможность выполнять различные операции над массивами и матрицами. В машинном обучении многие операции работы с данными могут быть представлены, как операции из линейной алгебры. Именно поэтому знание этой библиотеки очень важно.

Для начала познакомимся с базовым объектом в numpy - numpy.ndarray

In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 4])

Код выше создал вектор длины 3. Теперь мы можем выполнять различные арифметические операции над этим вектором.

In [3]:
array

array([1, 2, 4])

In [4]:
array * 2

array([2, 4, 8])

In [5]:
array + 5

array([6, 7, 9])

Мы можем выполнять поэлементные операции на массивах одинаковой длины.

In [6]:
array_2 = np.array([9, 2, 0])

In [8]:
array + array_2

array([10,  4,  4])

In [9]:
array * array_2

array([9, 4, 0])

С массивами можно работать как с листами и вытаскивать оттуда элементы по индексу. В тоже время, можно использовать индексацию по условию и вытаскивать элементы с помощью булевой маски.

In [12]:
array

array([1, 2, 4])

In [10]:
array[1]

2

In [11]:
array[1:]

array([2, 4])

In [13]:
print(array_2 > 0)
print(array[array_2 > 0])

[ True  True False]
[1 2]


В numpy можно работать не только с векторами, но и с матрицами и массивами большей размерности. Давайте создадим матрицу, которая состоит из одних единиц.

In [14]:
matrix = np.ones((2, 4))

In [15]:
matrix.shape

(2, 4)

In [16]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Над матрицами мы можем выполнять все те же операции, что и над векторами. Также мы можем считать среднее, сумму как по всем элементам, так и вдоль осей.

In [17]:
np.sum(matrix)

8.0

In [18]:
np.sum(matrix, axis=1)

array([4., 4.])

Можем создавать случайный матрицы.

In [19]:
random_matrix = np.random.normal(size=(2, 2))
random_matrix

array([[ 0.40829069,  1.50170043],
       [-1.85109956,  0.03864024]])

Можем умножать матрицы и выполнять различные операции линейной алгебры.

In [20]:
matrix.T @ random_matrix

array([[-1.44280887,  1.54034067],
       [-1.44280887,  1.54034067],
       [-1.44280887,  1.54034067],
       [-1.44280887,  1.54034067]])

In [21]:
np.linalg.det(random_matrix)

2.7955734544686046

In [22]:
np.linalg.matrix_rank(random_matrix)

2